### ISSUE TITLE
Building Issues

### ISSUE THREAD

**Issue by ra1u** [nh2/hatrace#21]
I need some help getting correct packages together. Version of ptrace on my side seems to have missing   `peekNullTerminatedBytes`, and `peekNullWordTerminatedWords`, and package waitpid have missing  `FullStatus(..)` and `waitpidFullStatus`

Where should i get this packages from?

Full error:

	cabal build
	Preprocessing library for hatrace-0.1.0.0..
	Building library for hatrace-0.1.0.0..
	[5 of 6] Compiling System.Hatrace   ( src/System/Hatrace.hs, dist/build/System/Hatrace.o )

	src/System/Hatrace.hs:115:69: error:
		Module
		‘System.Linux.Ptrace’
		does not export
		‘peekNullTerminatedBytes’
		|
	115 | import           System.Linux.Ptrace (TracedProcess(..), peekBytes, peekNullTerminatedBytes, peekNullWordTerminatedWords, detach)
		|                                                                     ^^^^^^^^^^^^^^^^^^^^^^^

	src/System/Hatrace.hs:115:94: error:
		Module
		‘System.Linux.Ptrace’
		does not export
		‘peekNullWordTerminatedWords’
		|
	115 | import           System.Linux.Ptrace (TracedProcess(..), peekBytes, peekNullTerminatedBytes, peekNullWordTerminatedWords, detach)
		|                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^

	src/System/Hatrace.hs:127:49: error:
		Module ‘System.Posix.Waitpid’ does not export ‘waitpidFullStatus’
		|
	127 | import           System.Posix.Waitpid (waitpid, waitpidFullStatus, Status(..), FullStatus(..), Flag(..))
		|                                                 ^^^^^^^^^^^^^^^^^

	src/System/Hatrace.hs:127:80: error:
		Module ‘System.Posix.Waitpid’ does not export ‘FullStatus(..)’
		|
	127 | import           System.Posix.Waitpid (waitpid, waitpidFullStatus, Status(..), FullStatus(..), Flag(..))
		|

**Comment by qrilka** [comment]
Please see https://github.com/nh2/hatrace/blob/master/stack.yaml - `hatrace` uses forks of `linux-ptrace` and `posix-waitpid`
@nh2 didn't you want to create a PR for `posix-waitpid`? I guess maintainers won't react quickly but I guess it's better to have it

**Comment by nh2** [comment]
Yes, what @qrilka said is the correct explanation:

You need to use the patched versions of my dependencies.

@qrilka Yes, I plan to create PRs for that, but haven't yet because I don't know yet whether the changes made so far are all that's needed, or if it better be extended some more first.

**Comment by ra1u** [comment]
Than you both! I was able to get trough using stack.
